version: "3.9"

x-logging:
  &highlight-logging
    driver: fluentd
    options:
      fluentd-address: "otel.highlight.io:24224"
      fluentd-async: "true"
      fluentd-sub-second-precision: "true"
      tag: "highlight.project_id=jd4xv2xg"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ~/data/fotohive/images:/app/images
    depends_on:
      - db
    logging: *highlight-logging
  caddy:
    image: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy:/data/caddy
    logging: *highlight-logging

  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    volumes:
      - ~/data/fotohive/psql:/var/lib/postgresql/data/pgdata
    logging: *highlight-logging


