name: cd

on:
    push:
        branches: [main]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: alextldr/fotohive

jobs:
    build-and-deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Log in to Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  tags: |
                      type=ref,event=branch
                      type=sha,prefix=sha-

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

            - name: Deploy to Hetzner VM
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: 188.245.181.254
                  username: alex
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  passphrase: ${{ secrets.SSH_PASSPHRASE }}
                  script: |
                      # Login to GitHub Container Registry
                      echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

                      # Navigate to app directory (create if doesn't exist)
                      mkdir -p ~/fotohive
                      cd ~/fotohive

                      # Download docker-compose files
                      curl -sSL https://raw.githubusercontent.com/AlexTLDR/FotoHive/main/docker-compose.yml -o docker-compose.yml
                      curl -sSL https://raw.githubusercontent.com/AlexTLDR/FotoHive/main/docker-compose.production.yml -o docker-compose.production.yml

                      # Create override file to use pre-built image instead of building
                      cat > docker-compose.override.yml << EOF
                      services:
                        server:
                          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main
                          ports:
                            - "4000:4000"
                          environment:
                            - PSQL_HOST=${{ secrets.PSQL_HOST }}
                            - PSQL_PORT=${{ secrets.PSQL_PORT }}
                            - PSQL_USER=${{ secrets.PSQL_USER }}
                            - PSQL_PASSWORD=${{ secrets.PSQL_PASSWORD }}
                            - PSQL_DATABASE=${{ secrets.PSQL_DATABASE }}
                            - PSQL_SSLMODE=${{ secrets.PSQL_SSLMODE }}
                            - SMTP_HOST=${{ secrets.SMTP_HOST }}
                            - SMTP_PORT=${{ secrets.SMTP_PORT }}
                            - SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}
                            - SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
                            - CSRF_KEY=${{ secrets.CSRF_KEY }}
                            - CSRF_SECURE=${{ secrets.CSRF_SECURE }}
                            - SERVER_ADDRESS=${{ secrets.SERVER_ADDRESS }}
                            - DROPBOX_APP_ID=${{ secrets.DROPBOX_APP_ID }}
                            - DROPBOX_APP_SECRET=${{ secrets.DROPBOX_APP_SECRET }}
                      EOF

                      # Stop existing stack
                      docker compose -f docker-compose.yml -f docker-compose.production.yml -f docker-compose.override.yml down || true

                      # Pull the latest image
                      docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main

                      # Set environment variables for database service
                      export PSQL_USER="${{ secrets.PSQL_USER }}"
                      export PSQL_PASSWORD="${{ secrets.PSQL_PASSWORD }}"
                      export PSQL_DATABASE="${{ secrets.PSQL_DATABASE }}"

                      # Start the stack with environment variables
                      docker compose -f docker-compose.yml -f docker-compose.production.yml -f docker-compose.override.yml up -d

                      # Wait for containers to start
                      sleep 10

                      # Verify containers are running
                      docker compose -f docker-compose.yml -f docker-compose.production.yml -f docker-compose.override.yml ps

                      # Show logs if any container failed
                      if ! docker compose -f docker-compose.yml -f docker-compose.production.yml -f docker-compose.override.yml ps | grep -q "Up"; then
                        echo "Container startup failed. Showing logs:"
                        docker compose -f docker-compose.yml -f docker-compose.production.yml -f docker-compose.override.yml logs
                        exit 1
                      fi

                      echo "FotoHive deployment successful!"

                      # Clean up old images
                      docker image prune -f
